[package]
name = "fabrique-core"
version = "0.1.0"
edition = "2024"
description = "Core traits and types for the Fabrique ORM"
license = "MIT"
repository = "https://github.com/robinstraub/fabrique"
homepage = "https://github.com/robinstraub/fabrique"
documentation = "https://docs.rs/fabrique-core"


[dependencies]
sqlx = { workspace = true, optional = true }

[dev-dependencies]
fabrique-derive = { path = "../fabrique-derive", features = ["sqlx"] }
fabrique = { path = "../fabrique", features = ["sqlx"] }
sqlx = { workspace = true, features = ["runtime-tokio-rustls", "uuid"] }
uuid = "1"

[features]
default = []
sqlx = ["dep:sqlx"]
