[package]
name = "fabrique-core"
version = "0.2.1"
edition = "2024"
description = "Core traits and types for Fabrique"
license = "MIT"
repository = "https://github.com/robinstraub/fabrique"
homepage = "https://github.com/robinstraub/fabrique"
documentation = "https://docs.rs/fabrique-core"


[features]
postgres = ["sqlx/postgres"]
mysql = ["sqlx/mysql"]
sqlite = ["sqlx/sqlite"]
doctests = ["sqlite"]

[dependencies]
sqlx = { workspace = true }
thiserror = "2"

[dev-dependencies]
fabrique-derive = { path = "../fabrique-derive" }
fabrique = { path = "../fabrique" }
sqlx = { workspace = true, features = ["runtime-tokio", "uuid"] }
tokio = { version = "1", features = ["rt", "macros"] }
uuid = { version = "1", features = ["v4"] }
