[package]
name = "fabrique-core"
version = "0.1.1"
edition = "2024"
description = "Core traits and types for the Fabrique ORM"
license = "MIT"
repository = "https://github.com/robinstraub/fabrique"
homepage = "https://github.com/robinstraub/fabrique"
documentation = "https://docs.rs/fabrique-core"


[dependencies]
sqlx = { workspace = true }
thiserror = "2"

[dev-dependencies]
fabrique-derive = { path = "../fabrique-derive" }
fabrique = { path = "../fabrique" }
sqlx = { workspace = true, features = ["runtime-tokio", "uuid"] }
uuid = { version = "1", features = ["v4"] }
