# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

reviews:
  profile: assertive
  path_filters:
    - "!**/*.js"

knowledge_base:
  code_guidelines:
    enabled: true
    filePatterns:
      - "docs/README.md"
