[workspace]

members = ["fabrique-derive", "fabrique", "fabrique-core", "ui-tests"]

resolver = "3"

[workspace.dependencies]
sqlx = { version = "0.9.0-alpha.1", features = [
  "chrono",
  "runtime-tokio",
  "uuid",
] }
cargo-husky = { version = "1", default-features = false, features = [
  "user-hooks",
] }
fake = { version = "4", features = ["uuid", "chrono"] }
