[workspace]

members = ["fabrique-derive", "fabrique", "fabrique-core"]

resolver = "3"

[workspace.dependencies]
sqlx = { version = "0.9.0-alpha.1", features = [
  "runtime-tokio",
  "postgres",
  "uuid",
] }
cargo-husky = { version = "1", default-features = false, features = [
  "precommit-hook",
  "run-cargo-fmt",
  "run-cargo-clippy",
  "run-cargo-test",
] }
