[workspace]
changelog_update = false
changelog_path = "./CHANGELOG.md"

[[package]]
name = "fabrique"
changelog_update = true
version_group = "fabrique"
publish_features = ["sqlite", "testing"]

[[package]]
name = "fabrique-core"
version_group = "fabrique"
publish_features = ["sqlite"]

[[package]]
name = "fabrique-derive"
version_group = "fabrique"
publish_features = ["sqlite", "testing"]
