use fabrique::prelude::*;
use uuid::Uuid;

// The messages() method is auto-generated from Message's belongs_to
// annotations.
#[derive(Clone, Debug, Default, Factory, PartialEq, Model)]
pub struct User {
    pub id: Uuid,
    pub name: String,
    pub email: String,
}

#[derive(Debug, Default, Factory, PartialEq, Model)]
pub struct Message {
    pub id: Uuid,
    #[fabrique(belongs_to = "User", alias = "Sender")]
    pub sender_id: Uuid,
    #[fabrique(belongs_to = "User", alias = "Recipient")]
    pub recipient_id: Uuid,
    pub content: String,
}

// messages::<Alias>() is now auto-generated by Message's derive(Model)
// via HasManyCodegen from the child side.

#[fabrique::test]
async fn test_load_messages_by_alias(pool: Pool<Sqlite>) {
    let sender = User::factory().create(&pool).await.unwrap();
    let recipient = User::factory().create(&pool).await.unwrap();

    Message::factory()
        .for_recipient(&recipient)
        .for_sender(&sender)
        .create(&pool)
        .await
        .unwrap();

    let sent = sender.messages::<_, Sender>().get(&pool).await.unwrap();
    assert_eq!(sent.len(), 1);

    let received = recipient
        .messages::<_, Recipient>()
        .get(&pool)
        .await
        .unwrap();
    assert_eq!(received.len(), 1);

    let received_by_sender = sender.messages::<_, Recipient>().get(&pool).await.unwrap();
    assert_eq!(received_by_sender.len(), 0);
}
