[package]
name = "fabrique-derive"
version = "0.1.1"
edition = "2024"
description = "Derive macros for the Fabrique ORM"
license = "MIT"
repository = "https://github.com/robinstraub/fabrique"
homepage = "https://github.com/robinstraub/fabrique"
documentation = "https://docs.rs/fabrique-derive"

[lib]
proc-macro = true

[dependencies]
aquamarine = { workspace = true }
darling = "0.21"
fabrique-core = { path = "../fabrique-core", version = "0.1.1" }
heck = "0.5"
proc-macro2 = "1.0"
quote = "1.0"
sqlx = { workspace = true, features = ["postgres", "runtime-tokio", "uuid"] }
syn = { version = "2.0", features = ["extra-traits"] }
thiserror = "2.0"

[dev-dependencies]
fabrique = { path = "../fabrique" }
fabrique-derive = { path = "." }
trybuild = "1.0"
uuid = "1"
