use std::marker::PhantomData;

/// Trait for objects that can be persisted to a database or storage backend.
///
/// This trait enables factories to create and persist objects using the `create()` method.
/// The trait is designed to be flexible, allowing different connection types and error handling
/// strategies based on your specific database or persistence layer.
///
/// # Example
///
/// ```rust
/// use fabrique::Persistable;
/// use uuid::Uuid;
///
/// #[derive(Persistable)]
/// struct Anvil {
///     id: Uuid,
///     name: String,
///     weight: i16,
/// }
/// ```
pub trait Persistable: Sized {
    /// The connection type used for database operations (e.g., database connection pool)
    type Connection: Clone + Sync;

    /// The error type returned by persistence operations
    type Error;

    /// The query builder type for constructing database queries
    #[cfg(feature = "sqlx")]
    type QueryBuilder: QueryBuilder;

    /// Creates a new query builder for this model.
    ///
    /// This method returns a query builder that allows chaining where clauses
    /// to construct type-safe database queries with compile-time column validation.
    #[cfg(feature = "sqlx")]
    fn query() -> Self::QueryBuilder;

    /// Creates and persists this object using the provided connection.
    ///
    /// This method should handle the actual database insertion or persistence logic
    /// and return the created object with any auto-generated fields (like IDs) populated.
    fn create(
        self,
        connection: &Self::Connection,
    ) -> impl Future<Output = Result<Self, Self::Error>> + Send;

    /// Retrieves all instances of this model from the persistence layer
    ///
    /// This method should handle querying the persistence layer for all records
    /// and return them as a vector of model instances.
    fn all(
        connection: &Self::Connection,
    ) -> impl Future<Output = Result<Vec<Self>, Self::Error>> + Send;
}

/// Marker type that associates a column name with its value type.
///
/// This type is used to provide compile-time type safety when building queries,
/// ensuring that the value passed to a where clause matches the expected type
/// for that column. Column markers are typically generated as constants by the
/// derive macro.
pub struct ColumnMarker<T> {
    /// The name of the database column
    pub name: &'static str,
    _phantom: PhantomData<T>,
}

impl<T> ColumnMarker<T> {
    /// Creates a new column marker with the specified name.
    ///
    /// This is a const function to allow generating column constants at compile time.
    pub const fn new(name: &'static str) -> Self {
        Self {
            name,
            _phantom: PhantomData,
        }
    }
}

/// Trait for building type-safe database queries.
///
/// Query builders enable constructing SQL queries with compile-time safety by requiring
/// column names to be static strings. This prevents dynamic column name injection while
/// providing a fluent, chainable API for building complex queries.
#[cfg(feature = "sqlx")]
pub trait QueryBuilder {
    /// Adds a WHERE clause to the query.
    ///
    /// This method appends a condition to the query using the specified column, operator,
    /// and value. Multiple where clauses can be chained together to build complex queries.
    fn r#where<T>(self, column: ColumnMarker<T>, operator: &'static str, value: T) -> Self
    where
        T: 'static + for<'q> sqlx::Encode<'q, sqlx::Postgres> + sqlx::Type<sqlx::Postgres>;
}

// Column constants are generated by the derive macro, for example:
// impl Anvil {
//     pub const ID: ColumnMarker<Uuid> = ColumnMarker::new("id");
//     pub const WEIGHT: ColumnMarker<i32> = ColumnMarker::new("weight");
// }
